server:
  port: ${CATALOG_PORT:8082}
  servlet:
    context-path: /catalog

spring:
  application:
    name: catalog-service

# TODO: Thêm datasource khi catalog-service có DB
# TODO: Thêm kafka config khi cần