server:
  port: ${IDENTITY_PORT:8081}
  servlet:
    context-path: /identity

spring:
  application:
    name: identity-service
  datasource:
    url: jdbc:postgresql://localhost:5433/${IDENTITY_DB:identity_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:admin123}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  signerKey: ${JWT_SIGNER_KEY}
