server:
  port: ${PAYMENT_PORT:8084}
  servlet:
    context-path: /payment

spring:
  application:
    name: payment-service

# TODO: Thêm datasource khi payment-service có DB
# TODO: Thêm kafka config khi cần