server:
  port: ${ORDER_PORT:8083}
  servlet:
    context-path: /order

spring:
  application:
    name: order-service

# TODO: Thêm datasource khi order-service có DB
# TODO: Thêm kafka config khi cần